### ISSUE TITLE
Exception in init undefined

### ISSUE THREAD

**Issue by calendarbase** [sdllc/controlr#2]
Installed on Ubuntu 14.04, R 3.4, Node 6.4

I tried the example code and got this error: 

/Dokument/node-r-test$ node index.js
Exception in init undefined
error undefined
fs.js:101
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, unlink '/tmp/r.27927752'
    at Error (native)

**Comment by calendarbase** [comment]
Tried with Node 6.2.0 and R 3.2 but got installation error:

npm install controlr --save

> controlr@2.1.3 install /home/zzzz/Dokument/node-r-test/node_modules/controlr
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/zzzz/Dokument/node-r-test/node_modules/controlr/build'
  CXX(target) Release/obj.target/controlr/src/controlr.o
g++: error: WARNING:: No such file or directory
g++: error: ignoring: No such file or directory
g++: error: environment: No such file or directory
g++: error: value: No such file or directory
g++: error: of: No such file or directory
g++: error: R_HOME: No such file or directory
make: *** [Release/obj.target/controlr/src/controlr.o] Error 1
make: Leaving directory `/home/zzzz/Dokument/node-r-test/node_modules/controlr/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/zzzz/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-143-generic
gyp ERR! command "/home/zzzz/.nvm/versions/node/v6.2.0/bin/node" "/home/zzzz/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/zzzz/Dokument/node-r-test/node_modules/controlr
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN rtest@1.0.0 No description
npm WARN rtest@1.0.0 No repository field.
npm ERR! Linux 3.13.0-143-generic
npm ERR! argv "/home/zzzz/.nvm/versions/node/v6.2.0/bin/node" "/home/zzzz/.nvm/versions/node/v6.2.0/bin/npm" "install" "controlr" "--save"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! controlr@2.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the controlr@2.1.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the controlr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs controlr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls controlr
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zzzz/Dokument/node-r-test/npm-debug.log
